### ISSUE TITLE
Make node-controller part of kvm-operator

### ISSUE THREAD

**Issue by r7vme** [giantswarm/kvm-operator-node-controller#2]
Initial idea about this project was inspired by Kubernetes [external cloud controllers](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller) and was planned to run inside cluster. 

But looks like for us better design would be to have this functionality as part of [kvm-operator](https://github.com/giantswarm/kvm-operator).

By fixing this issue we should implement node-controller functionality directly in kvm-operator.

**Comment by xh3b4sd** [comment]
What is the actual timeline for this? I do not want to let it fall under the table. This should be done soon IMO.

**Comment by r7vme** [comment]
This either picked up by Platform engineers. Or i can try to pick this after i finish with azure host cluster.

**Comment by xh3b4sd** [comment]
I will not take this. In the reviews I pointed out what I think should be done initially. You took the shortcut. You should fix it IMO. This is why I expressed my fear that we will never do it "right" in case we are not doing it initially. Because, you have more important things to do. I know this. This is the dilemma.

**Comment by xh3b4sd** [comment]
I was thinking about this a little bit. We have the drainer implementation in the `kvm-operator`. It makes sure that the pods we run on the host cluster, which serve the guest cluster nodes, are drained an deleted. I was thinking to hook in there and delete the node in the guest cluster as soon as it got drained. Now I am wondering if this is something we want to do in general. Then we should just add this to the `node-operator`. Does this make sense? 

Another thing I was wondering. Does the `kvm-operator-node-controller` also take care in case guest cluster nodes turn into not being ready just for any kind of reason? Is this even a good thing then? So isn't this a problem we have in all providers? In case this is a general thing we should just add a general watch for all nodes of all guest clusters to `node-operator`.

**Comment by r7vme** [comment]
> Then we should just add this to the node-operator. Does this make sense?

Having this in `node-operator` can make sense.

> Does the kvm-operator-node-controller also take care in case guest cluster nodes turn into not being ready just for any kind of reason?

Do you have an example, when kubernetes itself can not handle this? for me `NotReady` caused by real VM/pod deletetion is only corner case that Kubernetes can not cover on it's own in on-prem installation.

The other use case can be proactive VM roll out in case of issues (e.g. docker crash), but this is another story imo.

**Comment by xh3b4sd** [comment]
> real VM/pod deletetion is only corner case that Kubernetes can not cover on it's own in on-prem installation

Ok then lets keep it to KVM. Works for me. Just trying to get the concept right in my head. Since this is about deletion. This is about deletion of the pods we run on the host cluster, right? In this case we can quite easily integrate this into the drainer controller in the kvm-operator because we listen on delete events for the pods there already. Do you think this is a good idea to do it this way? Or do you have anything in mind that would speak against it? What happens when the kubelet dies and we want to remove the node from the guest cluster but the pod is not being deleted? This can happen right? Then the suggested approach would not work and we would need to introduce a new controller in the kvm-operator that reconciles differently. 

Also can you describe the test case we have to ensure to work when we move this functionality to the kvm-operator?

**Comment by r7vme** [comment]
> Then the suggested approach would not work and we would need to introduce a new controller in the kvm-operator that reconciles differently.

Yes, +1 for new controller. But please note we don't really need to handle any extra cases. Only use case we are addressing in "kvm-operator-node-controller" is GC of nodes that were removed from cloud provider. This is only functionality that is missing in "on-prem" kubernetes cloud-provider code and exists in AWS/Azure/GCE/others cloud-providers.

> Also can you describe the test case we have to ensure to work when we move this functionality to the kvm-operator?

Test case 1:
1. Remove kvm pod
2. Wait 2 minutes (enough to become NotReady and checked by kvm-operator-node-controller)
3. Make sure node has been removed from kubernetes

Test case 2:
1. Stop kubelet on node
2. Wait 2 minutes
3. Make sure node stays in `NotReady` state in kubernetes

**Comment by xh3b4sd** [comment]
Is there a specific timing issue? Does it matter that we do this within, say, 30 seconds or something? Or is it only important to do it eventually? Or is it that it is better the faster we remove kubelets from the API where no nodes are available anymore?

**Comment by r7vme** [comment]
Just a balance between speed and API load.

10 minutes is definitely too long. We want apps to be respawned on healthy node faster.
5 seconds will spam API with constant unnecessary load.
